name: warmly_bot
publish_to: 'none'
description: Telegram bot for warmly app
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  teledart: ^0.6.1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
